# Generated by Django 5.2.1 on 2025-05-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('roll_num', models.IntegerField(unique=True)),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
