# Generated by Django 5.2.1 on 2025-05-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_student_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
    ]
